# Generated by Django 2.2.5 on 2019-09-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shopuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='phone',
            field=models.IntegerField(blank=True, default=6),
            preserve_default=False,
        ),
    ]
