# Generated by Django 2.2.5 on 2019-09-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190918_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.IntegerField(blank=True, max_length=50),
        ),
    ]
