# Generated by Django 2.2.5 on 2019-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190918_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.IntegerField(blank=True, max_length=100),
        ),
    ]
