# Generated by Django 2.2.5 on 2019-09-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190918_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
