# Generated by Django 2.2.5 on 2019-09-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='death',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
